name: Check formatting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt -y install shfmt clang-format
      - name: Initial setup
        run: ./bootstrap.sh
      - name: Configure
        run: ./configure --enable-debug
      - name: Check formatting
        run: make check-format
